### ISSUE TITLE
URL error in default scenario

### ISSUE THREAD

**Issue by kingaza** [calipho-sib/sparql-playground#1]
Run start.bat under win7.

It seems all things are OK:
16:02:35.933 [main] INFO  c.i.s.s.t.r.SesameRepository - Initializing in memory repository
16:02:35.993 [main] INFO  c.i.s.s.t.r.SesameRepository - Loading turtle files from default\ttl-data
16:02:36.049 [main] DEBUG c.i.s.s.t.r.SesameRepository - Loading default\ttl-data\ontology.ttl
16:02:36.241 [main] DEBUG c.i.s.s.t.r.SesameRepository - Loading default\ttl-data\resource.ttl
16:02:36.254 [main] INFO  c.i.s.s.t.r.SesameRepository - Loading turtle files finished in 205 ms
16:02:38.617 [main] INFO  c.i.sib.sparql.tutorial.Application - Started Application in 11.757 seconds (JVM running for 14.805)
16:02:38.618 [main] INFO  c.i.sib.sparql.tutorial.Application - server.port option found. Taking port 8888
16:02:38.618 [main] INFO  c.i.sib.sparql.tutorial.Application - Server started at http://localhost:8888

However, on the webpage I see some message:
               endpoint: undefined/sparql
and 
               URL not found

If I try to "Reload Turtle Data ", I only get a message of "error undefined"
and a log "16:05:18.286 [http-nio-8888-exec-7] WARN  o.s.web.servlet.PageNotFound - Request method 'PUT' not supported"

**Comment by ddtxra** [comment]
Hello @kingaza ,
Thanks for reporting this bug.
Looks like a browser issue. Can you tell me which browser and version are you using (chrome, firefox, internet explorer)?

If you type:
http://localhost:8888/sparql?query=SELECT%20DISTINCT%20*%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo%0A%7D%0ALIMIT%2010&output=json

Do you get something?

**Comment by kingaza** [comment]
Hello @ddtxra ,

You shall be right that the problem is caused by my IE10. I can get response via your url request.
btw, it is OK with IE11 under my another Win7 and safari under Mac.

**Comment by ddtxra** [comment]
Hello @kingaza 
It's good to know that!
I have issued a pre-release (1.3.1) with support for IE10.
https://github.com/calipho-sib/sparql-playground/archive/v1.3.1.zip

Could you tell me if it works on your environment?
Thanks in advance!

**Comment by kingaza** [comment]
I tried your archive again and again, but still failed. Maybe there is something wrong in my environment?
How can I get more trace message for it?

**Comment by ddtxra** [comment]
Sorry @kingaza I made a mistake with the release 1.3.1...
I have release version 1.3.2 that is now working with IE 10: https://github.com/calipho-sib/sparql-playground/archive/v1.3.2.zip

Give it a try!
On http://sparql-playground.isb-sib.ch/ you may need to clear your cache.

Cheers, 
I hope you enjoy!

I will close the issue for now, but if you find some other issues on IE10 let me know.

**Comment by ddtxra** [comment]
Just to make sure, did the version 1.3.2 worked on your environment or the website http://sparql-playground.isb-sib.ch/ @kingaza ?

**Comment by kingaza** [comment]
hello @ddtxra ,

Sorry for the late reply, due to my vacation. 
The version 1.3.2 works very well on my IE10 now. 
thx a lot for your quick response.  ;-)

**Comment by ddtxra** [comment]
welcome! Enjoy :+1:
