### ISSUE TITLE
Permalink queries

### ISSUE THREAD

**Issue by lolive** [calipho-sib/sparql-playground#9]
Is there a way to permalink queries?

**Comment by ddtxra** [comment]
yes, simple use the URL. e.g. https://sparql-playground.sib.swiss/?query=select%20%3Fthing%20where%20%7B%0A%20%20%3Fthing%20rdf:type%20dbo:Person%20.%0A%7D%0A%0A%23%20Remember%20that%20in%20the%20turtle%20data%20(Data%20tab)%20we%20can%20see:%20%0A%23%0A%23%20%27ttr:John%20a%20dbo:Person%27%0A%23%0A%23%20%27a%27%20can%20also%20be%20used%20instead%20of%20%27rdf:type%27%20%0A%23%20%27a%27%20is%20a%20synonym%20of%20%27rdf:type%27%0A%0A%23%20The%20name%20of%20the%20variable%20can%20have%20any%20value%0A%0A%23%20Explore%20snorql:%0A%23%0A%23%20Click%20on%20ttr:William%20to%20see%20the%20properties%20attached%20to%20it&output=html
